"{\"data\": [\"Postgres initialized\", \"\\u2514\\u2500 Opening connection to PostgreSQL database...DONE\", \"\", \"Exporting data from upstream block fill_in_missing_values to mage.dev_example_pipeline_fill_in_missing_values_v1.\", \"\\r\\u251c\\u2500 \", \"\\u2514\\u2500 Exporting data to 'mage.demo'...DONE\\r\\u251c\\u2500 \", \"\\u2514\\u2500 Loading data...DONE\", \"\", \"/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py:162: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\", \"  return read_sql(\", \"Postgres initialized\", \"\\u2514\\u2500 Opening connection to PostgreSQL database...DONE\", \"\", \"Exporting data from upstream block fill_in_missing_values to mage.dev_example_pipeline_fill_in_missing_values_v1.\", \"\\r\\u251c\\u2500 \", \"\\u2514\\u2500 Exporting data to 'mage.demo'...DONE\\r\\u251c\\u2500 \", \"\\u2514\\u2500 Loading data...DONE\", \"\", \"/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py:162: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\", \"  return read_sql(\", \"\"], \"error\": null, \"execution_state\": null, \"metadata\": null, \"msg_id\": \"a3b8f67b-6ef3350ad6daf0b566e855fd_7_9\", \"msg_type\": \"stream\", \"type\": \"text/plain\", \"uuid\": \"crimson_shadow\", \"pipeline_uuid\": null}"